package org.vesselonline.mail;

public class DailyBriefingException extends Exception {
  /**
   * For Serializable interface, value generated by Eclipse.
   */
  private static final long serialVersionUID = -5951256697740259701L;

  public DailyBriefingException() {
    super();
  }

  public DailyBriefingException(String message) {
    super(message);
  }

  public DailyBriefingException(String message, Throwable throwable) {
    super(message, throwable);
  }

  public DailyBriefingException(Throwable throwable) {
    super(throwable);
  } 
}
